### PR TITLE
Mark the Non Reportable flag as true when the user Id of the delegate matches the user Id of the admin record of the supervisor being selected.

### PR DESCRIPTION
**Pull request by ABSinhaa**
### JIRA link
[TD-4751](https://hee-tis.atlassian.net/browse/TD-4751)

### Description
Updated the Non Reportable flag using inline SQL query to add the logic for making Non Reportable property value as TRUE when the delegate's user ID matches the admin User Id of the supervisor selected. 

### Screenshots
No UI Screenshots as the flag should appear on the DB and not the UI.
image

image

image

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [x] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [x] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

[TD-4751]: https://hee-tis.atlassian.net/browse/TD-4751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Auldrin-Possa — COMMENTED** [review]
Is there any specific need of changing method signature ( passing adminUserId param)?
It seems that, in the DataService method, value is being retrieved from DB table

**Comment by ABSinhaa** [comment]
@Auldrin-Possa : No specific need to change the signature, but I added it thinking of a future scenario where we read that value from the UI, kept it nullable and the references have been updated accordingly.

**Comment by Auldrin-Possa** [comment]
@ABSinhaa Modified service method is being used for POST (enrol self assessment) operation. I recommend removing the extra parameter. @rshrirohit pls share your view on this.

**Comment by ABSinhaa** [comment]
Hi @Auldrin-Possa, I have removed the unused adminUserId variable from the method signature. 

cc : @rshrirohit

**Review by Auldrin-Possa — COMMENTED** [review]
Looks good.

**Pull request merged**
