### PR TITLE
TD-1111 Adding google analytic and Hotsjar service

### PR DESCRIPTION
**Pull request by sherif-olaboye**
### JIRA link
https://hee-tis.atlassian.net/browse/TD-1111

### Description
TD-1111

### Screenshots
_Attach screenshots on mobile, tablet and desktop._

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [ ] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

### CODE REVIEW

**Comment by kevwhitt-hee** [comment]
@sherif-olaboye, this change has conflicts that need resolving. I can only see references to Google analytics and tag manager in the changed files but the PR mentions Hotjar - how has this been installed?
Please could you start PR names with the ticket ID "TD-1111" so that they get linked to the Jira ticket?
Please could you use the checklist to indicate what checks you have done when raising the PR?

**Comment by sherif-olaboye** [comment]
The Hotsjar was added by adding  JavaScript on the body and footer of the layout while the javascript added on the head was for the google analytic service

**Comment by kevwhitt-hee** [comment]
> The Hotsjar was added by adding JavaScript on the body and footer of the layout while the javascript added on the head was for the google analytic service

Hi @sherif-olaboye, in the list of files changed: https://github.com/TechnologyEnhancedLearning/DLSV2/pull/1743/files 
I can see one file has changed and everything in there appears to relate to Google tag manager. I can't see any reference to Hotjar - which line is it on?

**Comment by sherif-olaboye** [comment]
Yes because Hotsjar can be implemented using Google Tag Manager or Hotsjar service but Google Tag Manager gives more flexibility and it is Google Tag Manager that is use to implement Hotsjar

**Comment by kevwhitt-hee** [comment]
Thanks @sherif-olaboye, makes sense now. A new merge conflict has crept in, please could you resolve this and then we can get this merged?

**Review by kevwhitt-hee — APPROVED** [review]

**Pull request merged**
