### PR TITLE
DLSV2-151 Reads min and max values from database in service method

### PR DESCRIPTION
**Pull request by kevwhitt-hee**
And tweaks tests and calls accordingly

### CODE REVIEW

**Comment by FridaTveit** [comment]
@kevwhitt-hee looks like this breaks the data tests with the error `Invalid column name 'CompetencyGroupID'`. Do you know why that is? Has that column been added to the db? Do the data tests work locally for you? 🙂

**Comment by kevwhitt-hee** [comment]
Argh! Trying to fix a bug with the self-assessments and need to tweak a service call to make it work with my dev database (which has changes relating to another branch) and mistakenly checked it in. Fixing now - my bad :(

**Comment by FridaTveit** [comment]
I see, no worries 🙂

**Comment by FridaTveit** [comment]
@kevwhitt-hee just so you're aware I'm still seeing failing tests on master. Specifically `SetResultForCompetency_does_not_set_result_for_invalid_question`, `SetResultForCompetency_does_not_set_result_for_invalid_result` and `SetResultForCompetency_does_not_set_result_for_negative_result`. They all give a `NullReferenceException`. Looks like it's from trying to access `assessmentQuestion.MinValue` in the `SetResultForCompetency` method. I assume because the select returns `NULL` as the assessment question id is invalid 🙂

**Comment by kevwhitt-hee** [comment]
Sorry, @FridaTveit . Had a nightmare with this one. Should be good, now. :)

**Comment by FridaTveit** [comment]
Yes all appears to be working now, thanks! 🙂

**Pull request merged**
