### PR TITLE
TD-1046-Passporting: Issue with the Completed/Available Activities links on the 'Learning Portal'

### PR DESCRIPTION
**Pull request by Auldrin-Possa**
**JIRA link**
https://hee-tis.atlassian.net/browse/TD-1046

**Description**
code added to check completed activities.

**Screenshots**
N/A

-----
### Developer checks
I have:
- [ ] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript
- [x] Tested any Views or partials created or changed with [Wave Chrome plugin]
- [ ] Updated/added documentation in [Confluence]
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [x] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

### CODE REVIEW

**Comment by kevwhitt-hee** [comment]
What problem is this change fixing, @Auldrin-Possa ?

**Comment by Auldrin-Possa** [comment]
> What problem is this change fixing, @Auldrin-Possa ?

Launch Course (Current/Completed/Available) can also be called from Tracking System->Courses along with the respective activity menu click.
For some courses, the request is passed to CoursePassword or Section, and so on. The reason DB hit is required to check the activity status in each section.

**Comment by kevwhitt-hee** [comment]
> > What problem is this change fixing, @Auldrin-Possa ?
> 
> Launch Course (Current/Completed/Available) can also be called from Tracking System->Courses along with the respective activity menu click. For some courses, the request is being passed to CoursePassword or Section, tutorial, and so on. Due to this, DB hit is required to check the activity status in each section.

What happens if the user launches the course directly from a link (e.g. bookmark) do we have a fallback/default "Current courses" breadcrumb in this scenario or is it handled some other way?

**Comment by Auldrin-Possa** [comment]
> > > What problem is this change fixing, @Auldrin-Possa ?
> > 
> > 
> > Launch Course (Current/Completed/Available) can also be called from Tracking System->Courses along with the respective activity menu click. For some courses, the request is being passed to CoursePassword or Section, tutorial, and so on. Due to this, DB hit is required to check the activity status in each section.
> 
> What happens if the user launches the course directly from a link (e.g. bookmark) do we have a fallback/default "Current courses" breadcrumb in this scenario or is it handled some other way?

Bookmarks call the same controller method where the check is added to test the status of the course. This will show the correct menu link.

**Review by kevwhitt-hee — APPROVED** [review]

**Pull request merged**
