### PR TITLE
Heedls 415 admin page pagination

### PR DESCRIPTION
**Pull request by AlexJacksonDS**
Round 2 with actually correct filter text. Should have checked more closely that they were actually working.

### CODE REVIEW

**Review by DanBloxham-sw — COMMENTED** [review]
This is looking good, but I think the diagnostic one will need to be changed from "HasDiagnostic,DiagnosticsScore" to "HasDiagnostic,DiagnosticScore" (making "Diagnostics" singular before the score)

**Comment by AlexJacksonDS** [comment]
Yep, good spot. Missed the extra s

**Review by DanBloxham-sw — APPROVED** [review]

**Comment by stellake** [comment]
Just double checking if we've made sure all refactored properties work as expected?

**Comment by DanBloxham-sw** [comment]
When I tested previously, each one in that list worked except for the three being changed.

**Comment by AlexJacksonDS** [comment]
And I've checked that these ones I've just changed work locally

**Review by stellake — APPROVED** [review]
Given that all the refactored search properties are tested, happy for merge! 👍

**Pull request merged**
