### PR TITLE
TD-899 allow supervisors to supervise self assessments a user is already enrolled on (TD-202 for UAR)

### PR DESCRIPTION
**Pull request by OluwatobiAwe**
### JIRA link
[TD-899](https://hee-tis.atlassian.net/browse/TD-899)

### Description
Merge TD-202 changes, as well as further query changes(centre check, supervisor check and SelfAssessments.National check)

### Screenshots
_Attach screenshots on mobile, tablet and desktop._

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [x] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [x] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

[TD-899]: https://hee-tis.atlassian.net/browse/TD-899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by martinfoster-hee — COMMENTED** [review]
Looks good.

**Review by kevwhitt-hee — CHANGES_REQUESTED** [review]
@OluwatobiAwe, I am getting some errors when running this code. The SQL in the SupervisorService has been updated recently. Are your changes based on the latest version of them in the uar-test branch?
image

**Comment by OluwatobiAwe** [comment]
> @OluwatobiAwe, I am getting some errors when running this code. The SQL in the SupervisorService has been updated recently. Are your changes based on the latest version of them in the uar-test branch? image

I pulled in the latest code but I'm taking a closer look again

**Comment by OluwatobiAwe** [comment]
@kevwhitt-hee , Please kindly take another look

**Review by kevwhitt-hee — APPROVED** [review]

**Pull request merged**
