### PR TITLE
DLSV2-418 Consolidate the two JS select-all methods into one TS file

### PR DESCRIPTION
**Pull request by daniel-manta-hee**
### JIRA link
https://hee-dls.atlassian.net/browse/DLSV2-418

### Description
Move the code for selecting and deselecting checkboxes into a common location: checkboxes.ts.

-----
### Developer checks

Class Checkboxes in checkboxes.ts provides two ways for selecting and deselecting checkboxes: by group or by selector (e.g. a css class). 

Checks:

Check that the right method is being invoked when using the library. If it's passing a class, should be using selectAll and deselectAll. If it's a group, should use selectAllInGroup, deselectAllinGroup. 

There are some special cases like emailDelegates.ts. Originally it was importing two methods from common.ts and selecting by class name. When emailDelegates.ts calls setUpSelectAndDeselectButtons(), that is a local implementation, not the one originally in common which was not being imported here. So this call doesn't need to be renamed.

### CODE REVIEW

**Review by kevwhitt-hee — APPROVED** [review]
Code changes look good. All ACs met. Tested select all / deselect all JS functionality in all of the existing views that use them (that are already in master). No build errors. All tests passing.

**Comment by kevwhitt-hee** [comment]
Steve. I have reviewed and approved. Worth checking the weird BOM character error that you were seeing in TS files hasn't reappeared when you review, though.

**Comment by SteveJacksonSoft** [comment]
Thanks @kevwhitt-hee.
Some lint issues currently.

If you make sure you run...

* All the C# tests
* `npm run lint` in the web project
* `npm run test` in the web project

...before pushing your code for review, that should catch all the issues which might break the Jenkins build.

**Comment by kevwhitt-hee** [comment]
@SteveJacksonSoft, lint fixes have been applied. Please review.

**Comment by SteveJacksonSoft** [comment]
@daniel-manta-hee Doesn't look like you've pushed your changes...

**Comment by daniel-manta-hee** [comment]
@SteveJacksonSoft I've made an "amend" to my previous commit, pushed and synced from here. The [file common.ts can be seen in my pull request](https://github.com/TechnologyEnhancedLearning/DLSV2/pull/740/commits/fa7e60ec8d4a2165e8fd8a60d8d6b635f414ffc6#diff-fedcc18f47f1bcdeb95643d6c6f89cfd901f83684f4e8f39be687112e6568ff5). Perhaps timestamp not updated for that reason.

**Comment by SteveJacksonSoft** [comment]
@daniel-manta-hee Are you sure you force-pushed? Git would have complained if you pushed an amended commit and required you to force the push. I would expect a new commit with a new timestamp, and Jenkins is still throwing the same build errors.

**Comment by daniel-manta-hee** [comment]
Stephen, I'm making the change to appear as a new commit. Please try again.

**Comment by kevwhitt-hee** [comment]
@SteveJacksonSoft nudging you with a mention in case you didn't see Daniel's message.

**Comment by SteveJacksonSoft** [comment]
@daniel-manta-hee Yep, that's worked, merge away.

**Pull request merged**
