### PR TITLE
HEEDLS-627 Add css to fix the pagination button cursor

### PR DESCRIPTION
**Pull request by AlexJacksonDS**
### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-627

### Description
Added some css to fix the cursor being reset to default on the button

### Screenshots
image
image

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [x] Scanned over my own MR to ensure everything is as expected.

### CODE REVIEW

**Review by livzorn — APPROVED** [review]
Nice one!

**Review by SteveJacksonSoft — COMMENTED** [review]
It looks like there are pagination buttons in other partials in the project (search for files with `pagination` in the name and you'll see them. In particular, there's the minihub on the welcome page. What state are those partials in?

**Comment by AlexJacksonDS** [comment]
> It looks like there are pagination buttons in other partials in the project (search for files with `pagination` in the name and you'll see them. In particular, there's the minihub on the welcome page. What state are those partials in?

_SignpostingPaginationNav is the one I mentioned before on the HLD, that doesn't quite match the styling, but the cursors are fine.
RoleProfile/_Pagination is probably not fine, but also I don't really know why it has it's own partial
Minihub/_Pagination is fine
PaginatedPage/_Pagination and SearchablePage/_Pagination both use the same _PaginationNav partial I've just fixed

**Comment by SteveJacksonSoft** [comment]
> _SignpostingPaginationNav is the one I mentioned before on the HLD, that doesn't quite match the styling, but the cursors are fine. RoleProfile/_Pagination is probably not fine, but also I don't really know why it has it's own partial Minihub/_Pagination is fine PaginatedPage/_Pagination and SearchablePage/_Pagination both use the same _PaginationNav partial I've just fixed

I also meant to ask whether we could commonise any of these. Particularly the minihub one, though that would look like commonising the buttons just, since it has no page counter.

**Comment by AlexJacksonDS** [comment]
We can't commonise Minihub, since it has a completely different setup. It uses links and has different text with the buttons.

It would probably be possible to commonise the signposting and role profile ones

**Review by SteveJacksonSoft — APPROVED** [review]
Grand, let's leave it as is then.

**Pull request merged**
