### PR TITLE
TD-1943 adding header and aligning the header in the mobile view of c…

### PR DESCRIPTION
**Pull request by sherif-olaboye**
…ookie policy

### JIRA link
https://hee-tis.atlassian.net/browse/TD-1943

### Description
I needed to add inline css to align the mobile view header of the cookie policy

### Screenshots
image

image
image
-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [x] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

### CODE REVIEW

**Comment by kevwhitt-hee** [comment]
@sherif-olaboye, please could you add screenshots of the fixed mobile view to the PR description above so that we can see this change fixing the problem Madhavi saw?

**Review by Auldrin-Possa — COMMENTED** [review]
mobile view looks good, however, I can see some characters in the text.
image

image

**Comment by sherif-olaboye** [comment]
> @sherif-olaboye, please could you add screenshots of the fixed mobile view to the PR description above so that we can see this change fixing the problem Madhavi saw?

I have added the mobile view as requested

**Comment by sherif-olaboye** [comment]
> mobile view looks good, however, I can see some characters in the text. image
> 
> image

I have remove the character on the policy

**Review by kevwhitt-hee — APPROVED** [review]

**Pull request merged**
