### PR TITLE
TD-2314 remove the data.tests project

### PR DESCRIPTION
**Pull request by binon**
### JIRA link
https://hee-tis.atlassian.net/browse/TD-2314

### Description
I've successfully removed and backed up the Data.Tests Project from the DLS solution. It has been securely backed up on GitHub as a private repository "https://github.com/TechnologyEnhancedLearning/DigitalLearningSolutions.Data.Tests". During the removal process, I also had to address numerous dependencies and integrate them into Web.Tests project. As a result, the new configuration now builds without any issues, and after committing the changes, the CI pipeline also builds successfully.

image

### Screenshots
_Attach screenshots on mobile, tablet and desktop._

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [ ] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [ ] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

### CODE REVIEW

**Review by kevwhitt-hee — APPROVED** [review]
Looks good to me. All web tests are passing but 8 (which I'm struggling to locate) are not being run for some reason. Once tweaks have been made to the GitHub project readme (for example here: https://github.com/TechnologyEnhancedLearning/DLSV2#add-a-new-migration) to remove references to the data.tests project, I think this can be merged.

**Comment by kevwhitt-hee** [comment]
@rshrirohit we need to update the Confluence documentation on testing after this has been merged.

**Review by kevwhitt-hee — CHANGES_REQUESTED** [review]
Just need to remove references to the Data.Tests project in the project readme file. For example, here: https://github.com/TechnologyEnhancedLearning/DLSV2#add-a-new-migration

**Comment by binon** [comment]
@kevwhitt-hee , I have updated the Readme file in "https://github.com/TechnologyEnhancedLearning/DLSV2/tree/Develop/Features/TD-2314_Remove_the_Data.Tests_project"

Thanks
B

**Pull request merged**
