### PR TITLE
HEEDLS-620 Add word-break to several h1 elements with dynamic content

### PR DESCRIPTION
**Pull request by AlexJacksonDS**
### JIRA link
https://softwiretech.atlassian.net/browse/HEEDLS-620

### Description
Adds the word-break css class to various elements to prevent long course, group or delegate names overflowing the layout

### Screenshots
image
image
image

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [x] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [x] Scanned over my own MR to ensure everything is as expected.

### CODE REVIEW

**Review by JBsoftwire — APPROVED** [review]
Looks good.

**Review by SteveJacksonSoft — APPROVED** [review]
Cool, can you just mention on the ticket which pages you've changed?

**Comment by AlexJacksonDS** [comment]
> Cool, can you just mention on the ticket which pages you've changed?

I've already done this in a comment on the ticket.

**Comment by SteveJacksonSoft** [comment]
Nice, merge away.

**Pull request merged**
