### PR TITLE
Develop/feature/dlsv2 423 add new fields to selfassessment

### PR DESCRIPTION
**Pull request by ynhemanth**
### JIRA link
[DLSV2-423](https://hee-dls.atlassian.net/browse/DLSV2-423)

### Description
Added two fields QuestionLabel and DescriptionLabel to Selfassessment table 
on  LearningPortal/SelfAssessments/SelfAssessmentOverview table and Supervisor/ReviewSelfAssessment table
When QuestionLabel not null  column title “Question” is replaced by QuestionLabel value 

on Supervisor/ReviewCompetencySelfAsessment

When DescriptionLabel is not null title “Description” is replaced by DescritionLabel in  summary list

### Screenshots
image

image

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [Y ] Run the formatter and made sure there are no IDE errors.
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ Y] Manually tested my work with and without JavaScript. Full manual testing guidelines can be found here: https://softwiretech.atlassian.net/wiki/spaces/HEE/pages/6703648740/Testing
- [ ] Updated/added documentation in Swiki and/or Readme. Links (if any) are below:
  - [doc_1_here](link_1_here)
- [ Y] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken.
- [ Y] Scanned over my own MR to ensure everything is as expected.

### CODE REVIEW

**Review by kevwhitt-hee — CHANGES_REQUESTED** [review]
This seems to be mostly working except in the Supervisor/ReviewCompetencySelfAssessment view. I have changed my QuestionLabel to "Assessment" and my DescriptionLabel to "Guidance notes" for this self assessment but neither label appears here:
image

**Comment by kevwhitt-hee** [comment]
Another observation is that where you use:
```
var questionLabel = string.IsNullOrWhiteSpace(Model.DelegateSelfAssessment.QuestionLabel) ? "Question" :
                        Model.DelegateSelfAssessment.QuestionLabel;
```
In the page code block, unless this variable (@questionLabel) is being used multiple times on the page, the code should be inline, ie:
`@(string.IsNullOrWhiteSpace(Model.DelegateSelfAssessment.QuestionLabel) ? "Question" :                      Model.DelegateSelfAssessment.QuestionLabel)`

**Comment by ynhemanth** [comment]
image

**Comment by ynhemanth** [comment]
working now

**Review by kevwhitt-hee — CHANGES_REQUESTED** [review]
The "Description" field heading is displaying the "DescriptionLabel" when present now but the "Question" heading is using this also. It should be using the "QuestionLabel" string if present:
image

**Comment by ynhemanth** [comment]
Added updated

image

**Review by kevwhitt-hee — APPROVED** [review]
All good.

**Pull request merged**
