### PR TITLE
HEEDLS-283 - Section Page Show Post Learning Status

### PR DESCRIPTION
**Pull request by SChandarana**
image

### CODE REVIEW

**Review by FridaTveit — APPROVED** [review]
Looks good 🙂 Have you tested it with the percent complete hidden? Does it look okay?

**Comment by SChandarana** [comment]
I'll have a quick look at that now :)

**Comment by SChandarana** [comment]
Doesn't look out of place to me, what do you think?
image

**Comment by FridaTveit** [comment]
Yes, that looks fine. Thanks for checking 🙂

**Pull request merged**
