### PR TITLE
TD-2316 work through build warnings in the DLS repository resolving conflict

### PR DESCRIPTION
**Pull request by sherif-olaboye**
### JIRA link
https://hee-tis.atlassian.net/browse/TD-2316

### Description
I check the warning message to fix of the warning message in the CI build 

### Screenshots
_Attach screenshots on mobile, tablet and desktop._

-----
### Developer checks
(Leave tasks unticked if they haven't been appropriate for your ticket.)

I have:
- [x] Run the formatter and made sure there are no IDE errors (see [info on Text Editor settings](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546185813/DLS+Dev+Process) to avoid whitespace changes)
- [ ] Written tests for the changes (accessibility tests, unit tests for controller, data services, services, view models, etc)
- [ ] Manually tested my work with and without JavaScript
- [ ] Tested any Views or partials created or changed with [Wave Chrome plugin](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh/related) and addressed any valid accessibility issues
- [ ] Updated/added documentation in [Confluence](https://hee-tis.atlassian.net/wiki/spaces/TP/pages/3546939432/DLS+Code) and/or [GitHub Readme](https://github.com/TechnologyEnhancedLearning/DLSV2/blob/master/README.md). List of documentation links added/changed:
  - [doc_1_here](link_1_here)
- [ ] Updated my Jira ticket with information about other parts of the system that were touched as part of the MR and have to be sanity tested to ensure nothing’s broken
- [x] Scanned over my pull request in GitHub and addressed any warnings from the GitHub Build and Test checks.

### CODE REVIEW

**Comment by kevwhitt-hee** [comment]
This is looking good, @sherif-olaboye. I am still seeing some build warnings in the Data and Web projects:
image

It would be good to address these.

**Review by kevwhitt-hee — CHANGES_REQUESTED** [review]
This is a good start but I think there is more to be done here. See the "Unchanged files with check annotations" section on the files tab for examples of issue that still need to be addressed.

**Comment by sherif-olaboye** [comment]
> This is looking good, @sherif-olaboye. I am still seeing some build warnings in the Data and Web projects: image
> 
> It would be good to address these.

I have look into that and take of the warning

**Comment by sherif-olaboye** [comment]
> This is a good start but I think there is more to be done here. See the "Unchanged files with check annotations" section on the files tab for examples of issue that still need to be addressed.

I have check the "Unchanged files with check annotations" most of the files are class and method with obsolete which I think is deliberate

**Pull request merged**
